### ISSUE TITLE
[Server start] Improve message when elastic not launched/available

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1127]
Currently we see this:

```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/starlette/routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/starlette/routing.py", line 467, in default_lifespan
    await self.startup()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/starlette/routing.py", line 502, in startup
    await handler()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rubrix/server/server.py", line 101, in configure_elasticsearch
    raise ConfigError(
pydantic.errors.ConfigError: Your Elasticsearch endpoint at http://localhost:9200 is not available or not responding.
Please make sure your Elasticsearch instance is launched and correctly running and you have the necessary access permissions. Once you have verified this, restart the Rubrix server.
Error detail: [ConnectionError(<urllib3.connection.HTTPConnection object at 0x16fc94610>: Failed to establish a new connection: [Errno 61] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x16fc94610>: Failed to establish a new connection: [Errno 61] Connection refused)]
```

For improving readability I'd recommend removing the Error detail as it does not add anything meaningful and makes the clear message more difficult to read.

 Is this possible?

**Comment by frascuchon** [comment]
We can separate message in two logger calls with different logging level. From the point of view of a system manager, the error detail could be important to detect the problem. But it's true that we can enable by a `--verbose` logging param or something like that.

**Comment by dcfidalgo** [comment]
Not sure if this is possible, but I think for the "default user" it would already help if the "Error detail" came first, and then the "pydantic.errors.ConfigError".
