### ISSUE TITLE
[question] Potential dependency mismatch between FastAPI and Starlette?

### ISSUE THREAD

**Issue by dvsrepo** [recognai/rubrix#1271]
**Describe the bug**
Installing from source and including the server in a fresh `venv` raises the following:

`ERROR: fastapi 0.63.0 has requirement starlette==0.13.6, but you'll have starlette 0.19.0 which is incompatible.`

**To Reproduce**
To reproduce
```python
python -m venv venv
source venv/bin/activate
pip install .[server]
```

Then if we run `python -m rubrix` we get:
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/dani/recognai/rubrix101/venv/lib/python3.8/site-packages/rubrix/__main__.py", line 19, in <module>
    uvicorn.run(
  File "/Users/dani/recognai/rubrix101/venv/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
  File "/Users/dani/recognai/rubrix101/venv/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/dani/recognai/rubrix101/venv/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/Users/dani/recognai/rubrix101/venv/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/dani/recognai/rubrix101/venv/lib/python3.8/site-packages/uvicorn/importer.py", line 31, in import_from_string
    instance = getattr(instance, attr_str)
  File "/Users/dani/recognai/rubrix101/venv/lib/python3.8/site-packages/rubrix/utils.py", line 79, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Users/dani/recognai/rubrix101/venv/lib/python3.8/site-packages/rubrix/utils.py", line 111, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import rubrix.server.app because of the following error (look up to see its traceback):
cannot import name 'UJSONResponse' from 'starlette.responses' (/Users/dani/recognai/rubrix101/venv/lib/python3.8/site-packages/starlette/responses.py)
```

**Expected behavior**
Not sure if version ranges could be improved to avoid this, or there's something we could do

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]:
 - Rubrix Version [e.g. 0.10.0]: master
 - ElasticSearch Version [e.g. 7.10.2]: NA
 - Docker Image (optional) [e.g. rubrix:v0.10.0]:  NA

**Additional context**

**Comment by dcfidalgo** [comment]
Arg, I could reproduce this issue with a pip version <20.3, that is using the old deps resolver.

To solve this, I propose to make the starlette dependency of the client optional, that is if someone wants to use the monitoring feature, the user has to install starlette manually (as we do for other features like `to_datasets` or the `Snorkel` label model).

cc @frascuchon
