### ISSUE TITLE
reentrant error when start rubrix in docker

### ISSUE THREAD

**Issue by zelanastasia** [recognai/rubrix#1509]
Hello again. I'm trying to start rubrix in k8s, and at start in container i got error:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 533, in reap_workers
    os.WTERMSIG(status)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/glogging.py", line 261, in warning
    self.error_log.warning(msg, *args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1390, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1033, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 956, in handleError
    traceback.print_stack(frame, file=sys.stderr)
  File "/usr/local/lib/python3.7/traceback.py", line 190, in print_stack
    print_list(extract_stack(f, limit=limit), file=file)
  File "/usr/local/lib/python3.7/traceback.py", line 25, in print_list
    print(item, file=file, end="")
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 211, in run
    self.manage_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 573, in spawn_worker
    pid = os.fork()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 221, in _releaseLock
    def _releaseLock():
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 533, in reap_workers
    os.WTERMSIG(status)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/glogging.py", line 261, in warning
    self.error_log.warning(msg, *args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1390, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 367, in getMessage
    msg = str(self.msg)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 533, in reap_workers
    os.WTERMSIG(status)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/glogging.py", line 261, in warning
    self.error_log.warning(msg, *args, **kwargs)
Message: 'Worker with pid %s was terminated due to signal %s'
Arguments: (965651, 9)
```

Before this, a lot of worker trying to start and terminated due to signal 9.

 - OS: Ubuntu 20.04.2 LTS, Linux version 5.4.0-96-generic (buildd@lgw01-amd64-051) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))
 - Rubrix Version : 0.14.0
 - Docker Image:  master
 - CPU info: 
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       2
- k8s pod limits:
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi

I found some issues at gunicorn: https://github.com/benoitc/gunicorn/issues/2564
But it seems not helpful. 
Increase pod resources not help at all.

I will be grateful if you can help. If you need any information about my environment, i can provide it.

**Comment by frascuchon** [comment]
HI @zelanastasia and thanks for share

It's a quite weird problem. We would like to reproduce it in an isolated environment. Could you share the pod/services configuration and which Kubernetes version are you using?

Thanks a lot!

**Comment by zelanastasia** [comment]
@frascuchon 
This is manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubrix
  namespace: rubrix
  labels:
    name: rubrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rubrix
  template:
    metadata:
      labels:
        app: rubrix
    spec:
      containers:
        - name: rubrix
          env:
            - name: ELASTICSEARCH
              value: "https://${ES_USERNAME}:${ES_PASSWORD}@${ES_HOST}:9200"
            - name: RUBRIX_ELASTICSEARCH_SSL_VERIFY
              value: "False"
            - name: RUBRIX_LOCAL_AUTH_USERS_DB_FILE
              value: "/app/.users.yaml"
          image: recognai/rubrix:master
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 5Gi
            requests:
              cpu: 1
              memory: 5Gi
          ports:
            - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: rubrix
  namespace: rubrix
spec:
  type: LoadBalancer
  ports:
    - name: "6900"
      port: 6900
      targetPort: 80
  selector:
    app: rubrix
```

k8s version: v1.20.2

**Comment by frascuchon** [comment]
Hi @zelanastasia 

Reading about the error, it looks like some kind of worker's concurrency problem. You could try to limit the number of running workers by using some env var tunning.

Regarding the base [docker image documentation](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker) that we're using, you could try setting the [`WEB_CONCURRENCY`](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#web_concurrency) env var to "1". This could be enough, but you can also set the [`MAX_WORKERS`](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#max_workers) or the [`WORKERS_PER_CORE`](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#workers_per_core) to "1" to force the number of workers will be created.

We will include some guides to deploy rubrix in distributed containerized environments, like Kubernetes since it should be a bit different (See [here](https://fastapi.tiangolo.com/deployment/docker/#replication-number-of-processes))


Let me know if these changes worked. Thanks!

**Comment by zelanastasia** [comment]
@frascuchon yes, its worked. But i think that 1 worker is not enough for production.
Thank you anyway.

**Comment by frascuchon** [comment]
Hi @zelanastasia 

You could manage the number of workers at the Kubernetes level. You can increase the number of replicas in your deployment manifest and expose your service using a LoadBalancer ingress https://kubernetes.io/docs/concepts/services-networking/service/

**Comment by frascuchon** [comment]
I'll close this issue. Please, feel free you reopen it if you consider it.
