### ISSUE TITLE
ELASTICSEARCH env variable not being read properly

### ISSUE THREAD

**Issue by dhruvsakalley** [recognai/rubrix#2083]
**Describe the bug**
Did the environment variable name change?

`ELASTICSEARCH` enviornment variable is not being read properly on windows machine (no linux machine to test this). Prior to the name change Rubrix was able to use the `ELASTICSEARCH` setting correctly, upgrading the package cause this error:

```
  File "c:\dev\argenv\lib\site-packages\argilla\server\daos\backend\elasticsearch.py", line 90, in __exit__
    raise exception_value from exception_value
  File "c:\dev\argenv\lib\site-packages\argilla\server\daos\backend\elasticsearch.py", line 312, in _create_index
    if not self._index_exists(index):
  File "c:\dev\argenv\lib\site-packages\argilla\server\daos\backend\elasticsearch.py", line 249, in _index_exists
    return self.__client__.indices.exists(index)
  File "c:\dev\argenv\lib\site-packages\opensearchpy\client\utils.py", line 177, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "c:\dev\argenv\lib\site-packages\opensearchpy\client\indices.py", line 331, in exists
    return self.transport.perform_request(
  File "c:\dev\argenv\lib\site-packages\opensearchpy\transport.py", line 410, in perform_request
    raise e
  File "c:\dev\argenv\lib\site-packages\opensearchpy\transport.py", line 373, in perform_request
    status, headers_response, data = connection.perform_request(
  File "c:\dev\argenv\lib\site-packages\opensearchpy\connection\http_urllib3.py", line 268, in perform_request
    raise SSLError("N/A", str(e), e)
opensearchpy.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\dev\argenv\lib\site-packages\argilla\server\server.py", line 98, in configure_elasticsearch
    datasets: DatasetsDAO = DatasetsDAO.get_instance(
  File "c:\dev\argenv\lib\site-packages\argilla\server\daos\datasets.py", line 62, in get_instance
    cls._INSTANCE = cls(es, records_dao)
  File "c:\dev\argenv\lib\site-packages\argilla\server\daos\datasets.py", line 68, in __init__
    self.init()
  File "c:\dev\argenv\lib\site-packages\argilla\server\daos\datasets.py", line 72, in init
    self._es.create_datasets_index()
  File "c:\dev\argenv\lib\site-packages\argilla\server\daos\backend\elasticsearch.py", line 985, in create_datasets_index
    self._create_index(
  File "c:\dev\argenv\lib\site-packages\argilla\server\daos\backend\elasticsearch.py", line 309, in _create_index
    with backend_error_handler(index):
  File "c:\dev\argenv\lib\site-packages\argilla\server\daos\backend\elasticsearch.py", line 102, in __exit__
    raise GenericSearchError(ex)
argilla.server.daos.backend.elasticsearch.GenericSearchError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\dev\argenv\lib\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "c:\dev\argenv\lib\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "c:\dev\argenv\lib\site-packages\starlette\routing.py", line 598, in startup
    await handler()
  File "c:\dev\argenv\lib\site-packages\argilla\server\server.py", line 104, in configure_elasticsearch
    raise ConfigError(
pydantic.errors.ConfigError: Your Elasticsearch endpoint at https://elastic:XXXX@localhost:9200 is not available or not responding.
Please make sure your Elasticsearch instance is launched and correctly running and
you have the necessary access permissions. Once you have verified this, restart the argilla server.

```
While the variable is correctly set like so: 

![image](https://user-images.githubusercontent.com/3661965/208928003-4256851d-4990-4f05-9f59-b1c75079da2a.png)

**To Reproduce**
1. SET up elasticsearch outside of docker using SSL and then set `ELASTICSEARCH` environment variable. 
2. `pip install argilla[server]` followed by `python -m argilla`

**Expected behavior**
server start

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Argilla Version: 1.1.1
 - ElasticSearch Version: 8.2.0

**Additional context**
This was not the issue with rubrix, I can still login into Rubrix with a downgrade

**Comment by dvsrepo** [comment]
Thanks @dhruvsakalley !

@davidberenstein1957 is this similar to your issue with SSL certificates?

**Comment by dvsrepo** [comment]
As far as I see there's an issue with the SSL certificate. Maybe the elastic search client library changed from rubrix to Argilla and now it's throwing this more restrictive exception.

Reference 
https://stackoverflow.com/questions/12180552/openssl-error-self-signed-certificate-in-certificate-chain

**Comment by davidberenstein1957** [comment]
I am not entirely sure. @dhruvsakalley we had an issue with `httpx`, which was caused by having an _ in the URL. What happens if you were to set `verify=True` when connecting via `httpx`?

**Comment by dhruvsakalley** [comment]
You are correct @dvsrepo it does appear to be an SSL issue, will investigate further around signing the certificates.

**Comment by davidberenstein1957** [comment]
Let us know if you need any further help🤓

**Comment by davidberenstein1957** [comment]
@dhruvsakalley did you already manage to solve this?

**Comment by dhruvsakalley** [comment]
Hi @davidberenstein1957 I have for now disabled SSL but I will come back to this later this month, have other higher priority items, with SSL disabled it seems to work for the time being. I will update this towards the end of January

**Comment by davidberenstein1957** [comment]
Okay, we sometimes encountered an SSL error when there was an `_` in the hostname, could this be the issue for you too?

**Comment by dhruvsakalley** [comment]
Getting close to testing this next week, thank you for the patience.

**Comment by nataliaElv** [comment]
Hi @dhruvsakalley! Did you finally manage to figure out what the issue was?
