### ISSUE TITLE
Upgrade from 1.1.0 to 1.2.0 causes the server to not boot up

### ISSUE THREAD

**Issue by dhruvsakalley** [recognai/rubrix#2219]
**Describe the bug**
Upgrade from 1.1.0 to 1.2.0 causes the server to not boot up

**To Reproduce**
Upgrade from 1.1.0 to 1.2.0

**Expected behavior**
Server start 

**Logs**
```
c:\dev>pip install --upgrade  argilla[server]
Requirement already satisfied: argilla[server] in c:\python\lib\site-packages (1.1.0)
Collecting argilla[server]
  Using cached argilla-1.2.0-py3-none-any.whl (1.8 MB)
Requirement already satisfied: packaging>=20.0 in c:\python\lib\site-packages (from argilla[server]) (22.0)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in c:\python\lib\site-packages (from argilla[server]) (1.5.2)
Requirement already satisfied: monotonic in c:\python\lib\site-packages (from argilla[server]) (1.6)
Requirement already satisfied: deprecated~=1.2.0 in c:\python\lib\site-packages (from argilla[server]) (1.2.13)
Requirement already satisfied: numpy<1.24.0 in c:\python\lib\site-packages (from argilla[server]) (1.23.5)
Requirement already satisfied: tqdm>=4.27.0 in c:\python\lib\site-packages (from argilla[server]) (4.64.1)
Requirement already satisfied: pydantic>=1.7.1 in c:\python\lib\site-packages (from argilla[server]) (1.10.2)
Requirement already satisfied: backoff in c:\python\lib\site-packages (from argilla[server]) (1.11.1)
Requirement already satisfied: wrapt<1.15,>=1.13 in c:\python\lib\site-packages (from argilla[server]) (1.13.3)
Requirement already satisfied: httpx<0.24,>=0.15 in c:\python\lib\site-packages (from argilla[server]) (0.15.5)
Requirement already satisfied: smart-open in c:\python\lib\site-packages (from argilla[server]) (6.3.0)
Requirement already satisfied: aiofiles<22.2,>=0.6 in c:\python\lib\site-packages (from argilla[server]) (0.6.0)
Requirement already satisfied: PyYAML<6.1.0,>=5.4.1 in c:\python\lib\site-packages (from argilla[server]) (5.4.1)
Requirement already satisfied: opensearch-py<2.1,>=1.0 in c:\python\lib\site-packages (from argilla[server]) (1.0.0)
Requirement already satisfied: python-jose[cryptography]<3.4,>=3.2 in c:\python\lib\site-packages (from argilla[server]) (3.2.0)
Requirement already satisfied: scikit-learn>=0.24.2 in c:\python\lib\site-packages (from argilla[server]) (1.2.0)
Requirement already satisfied: brotli-asgi<1.3,>=1.1 in c:\python\lib\site-packages (from argilla[server]) (1.1.0)
Requirement already satisfied: psutil<5.10,>=5.8 in c:\python\lib\site-packages (from argilla[server]) (5.8.0)
Requirement already satisfied: uvicorn[standard]<0.21.0,>=0.15.0 in c:\python\lib\site-packages (from argilla[server]) (0.17.6)
Requirement already satisfied: passlib[bcrypt]~=1.7.4 in c:\python\lib\site-packages (from argilla[server]) (1.7.4)
Requirement already satisfied: python-multipart~=0.0.5 in c:\python\lib\site-packages (from argilla[server]) (0.0.5)
Requirement already satisfied: segment-analytics-python==2.2.0 in c:\python\lib\site-packages (from argilla[server]) (2.2.0)
Requirement already satisfied: elasticsearch<8.6.0,>=7.11.0 in c:\python\lib\site-packages (from argilla[server]) (8.5.3)
Requirement already satisfied: fastapi<0.89,>=0.75 in c:\python\lib\site-packages (from argilla[server]) (0.75.2)
Requirement already satisfied: luqum<0.13,>=0.11 in c:\python\lib\site-packages (from argilla[server]) (0.11.0)
Requirement already satisfied: requests~=2.7 in c:\python\lib\site-packages (from segment-analytics-python==2.2.0->argilla[server]) (2.28.1)
Requirement already satisfied: python-dateutil~=2.2 in c:\python\lib\site-packages (from segment-analytics-python==2.2.0->argilla[server]) (2.8.2)
Requirement already satisfied: brotli>=1.0.7 in c:\python\lib\site-packages (from brotli-asgi<1.3,>=1.1->argilla[server]) (1.0.9)
Requirement already satisfied: starlette>=0.13.4 in c:\python\lib\site-packages (from brotli-asgi<1.3,>=1.1->argilla[server]) (0.17.1)
Requirement already satisfied: elastic-transport<9,>=8 in c:\python\lib\site-packages (from elasticsearch<8.6.0,>=7.11.0->argilla[server]) (8.4.0)
Requirement already satisfied: anyio<4,>=3.0.0 in c:\python\lib\site-packages (from starlette>=0.13.4->brotli-asgi<1.3,>=1.1->argilla[server]) (3.6.2)
Requirement already satisfied: httpcore==0.11.* in c:\python\lib\site-packages (from httpx<0.24,>=0.15->argilla[server]) (0.11.1)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in c:\python\lib\site-packages (from httpx<0.24,>=0.15->argilla[server]) (1.5.0)
Requirement already satisfied: certifi in c:\python\lib\site-packages (from httpx<0.24,>=0.15->argilla[server]) (2022.12.7)
Requirement already satisfied: sniffio in c:\python\lib\site-packages (from httpx<0.24,>=0.15->argilla[server]) (1.3.0)
Requirement already satisfied: h11<0.10,>=0.8 in c:\python\lib\site-packages (from httpcore==0.11.*->httpx<0.24,>=0.15->argilla[server]) (0.9.0)
Requirement already satisfied: ply>=3.11 in c:\python\lib\site-packages (from luqum<0.13,>=0.11->argilla[server]) (3.11)
Requirement already satisfied: urllib3<2,>=1.21.1 in c:\python\lib\site-packages (from opensearch-py<2.1,>=1.0->argilla[server]) (1.26.13)
Requirement already satisfied: pytz>=2020.1 in c:\python\lib\site-packages (from pandas<2.0.0,>=1.0.0->argilla[server]) (2022.6)
Requirement already satisfied: bcrypt>=3.1.0 in c:\python\lib\site-packages (from passlib[bcrypt]~=1.7.4->argilla[server]) (4.0.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\python\lib\site-packages (from pydantic>=1.7.1->argilla[server]) (4.4.0)
Requirement already satisfied: pyasn1 in c:\python\lib\site-packages (from python-jose[cryptography]<3.4,>=3.2->argilla[server]) (0.4.8)
Requirement already satisfied: rsa in c:\python\lib\site-packages (from python-jose[cryptography]<3.4,>=3.2->argilla[server]) (4.9)
Requirement already satisfied: ecdsa<0.15 in c:\python\lib\site-packages (from python-jose[cryptography]<3.4,>=3.2->argilla[server]) (0.14.1)
Requirement already satisfied: six<2.0 in c:\python\lib\site-packages (from python-jose[cryptography]<3.4,>=3.2->argilla[server]) (1.16.0)
Requirement already satisfied: cryptography in c:\python\lib\site-packages (from python-jose[cryptography]<3.4,>=3.2->argilla[server]) (38.0.4)
Requirement already satisfied: scipy>=1.3.2 in c:\python\lib\site-packages (from scikit-learn>=0.24.2->argilla[server]) (1.9.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\python\lib\site-packages (from scikit-learn>=0.24.2->argilla[server]) (3.1.0)
Requirement already satisfied: joblib>=1.1.1 in c:\python\lib\site-packages (from scikit-learn>=0.24.2->argilla[server]) (1.2.0)
Requirement already satisfied: colorama in c:\python\lib\site-packages (from tqdm>=4.27.0->argilla[server]) (0.4.6)
Requirement already satisfied: click>=7.0 in c:\python\lib\site-packages (from uvicorn[standard]<0.21.0,>=0.15.0->argilla[server]) (8.1.3)
Requirement already satisfied: asgiref>=3.4.0 in c:\python\lib\site-packages (from uvicorn[standard]<0.21.0,>=0.15.0->argilla[server]) (3.5.2)
Requirement already satisfied: python-dotenv>=0.13 in c:\python\lib\site-packages (from uvicorn[standard]<0.21.0,>=0.15.0->argilla[server]) (0.21.0)
Requirement already satisfied: httptools>=0.4.0 in c:\python\lib\site-packages (from uvicorn[standard]<0.21.0,>=0.15.0->argilla[server]) (0.5.0)
Requirement already satisfied: watchgod>=0.6 in c:\python\lib\site-packages (from uvicorn[standard]<0.21.0,>=0.15.0->argilla[server]) (0.8.2)
Requirement already satisfied: websockets>=10.0 in c:\python\lib\site-packages (from uvicorn[standard]<0.21.0,>=0.15.0->argilla[server]) (10.4)
Requirement already satisfied: idna<4,>=2.5 in c:\python\lib\site-packages (from requests~=2.7->segment-analytics-python==2.2.0->argilla[server]) (3.4)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\python\lib\site-packages (from requests~=2.7->segment-analytics-python==2.2.0->argilla[server]) (2.1.1)
Requirement already satisfied: cffi>=1.12 in c:\python\lib\site-packages (from cryptography->python-jose[cryptography]<3.4,>=3.2->argilla[server]) (1.15.1)
Requirement already satisfied: pycparser in c:\python\lib\site-packages (from cffi>=1.12->cryptography->python-jose[cryptography]<3.4,>=3.2->argilla[server]) (2.21)
Installing collected packages: argilla
  Attempting uninstall: argilla
    Found existing installation: argilla 1.1.0
    Uninstalling argilla-1.1.0:
      Successfully uninstalled argilla-1.1.0
Successfully installed argilla-1.2.0

c:\dev>python -m argilla
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\argilla\utils\utils.py", line 111, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python\lib\site-packages\argilla\server\app.py", line 16, in <module>
    from argilla.server.server import app
  File "C:\Python\lib\site-packages\argilla\server\server.py", line 225, in <module>
    app_configure(argilla_app)
  File "C:\Python\lib\site-packages\argilla\server\server.py", line 111, in configure_app_statics
    temp_statics = _create_statics_folder(statics_folder)
  File "C:\Python\lib\site-packages\argilla\server\server.py", line 105, in _create_statics_folder
    for line in file:
  File "C:\Python\lib\fileinput.py", line 256, in __next__
    line = self._readline()
  File "C:\Python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6985: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\lib\site-packages\argilla\__main__.py", line 19, in <module>
    uvicorn.run(
  File "C:\Python\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Python\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Python\lib\site-packages\uvicorn\config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Python\lib\site-packages\uvicorn\importer.py", line 31, in import_from_string
    instance = getattr(instance, attr_str)
  File "C:\Python\lib\site-packages\argilla\utils\utils.py", line 81, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Python\lib\site-packages\argilla\utils\utils.py", line 113, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import argilla.server.app because of the following error (look up to see its traceback):
'charmap' codec can't decode byte 0x81 in position 6985: character maps to <undefined>
```

**Environment (please complete the following information):**
 - OS [e.g. iOS]: Windows Server 2019
 - Browser [e.g. chrome, safari]: NA
 - Argilla Version [e.g. 1.0.0]: 1.2.0
 - ElasticSearch Version [e.g. 7.10.2]: 8.3
 - Docker Image (optional) [e.g. argilla:v1.0.0]: NA

**Additional context**
Downgrading to 1.1.0 allows the server to boot.

**Comment by dvsrepo** [comment]
Thanks for reporting @dhruvsakalley, indeed this `_create_statics_folder` was introduced in `1.2.0`. @frascuchon will check this issue.

**Comment by frascuchon** [comment]
Thanks, @dhruvsakalley 

I'm tackling this one to be ready for the next patch release.

**Comment by frascuchon** [comment]
Hi, @dhruvsakalley to have a bit more context.

Could you share which system encoding is defined in your system by default?
```bash
python -c 'import locale; print( locale.getpreferredencoding())
```

If other than `UTF-8`, and as a workaround, could you try to launch argilla like this?:
```bash
set PYTHONUTF8=1 
python -m argilla
```
or 
```bash
python -Xutf8 -m argilla
```

See https://docs.python.org/3.11/using/windows.html#utf-8-mode

**Comment by keithCuniah** [comment]
Hi @dhruvsakalley,

I could reproduce the error and by running the second solution from @frascuchon, it works.

**Comment by dhruvsakalley** [comment]
Thank you, would be able to test this next week, much appreciate the prompt response.
