### ISSUE TITLE
RuntimeError: Failed to import argilla.server.app

### ISSUE THREAD

**Issue by jamnicki** [recognai/rubrix#2235]
Python v3.8.0, Win11

After `pip install "argilla[server]==1.2.0"`:

```powershell
>> python -m argilla

Traceback (most recent call last):
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\utils\utils.py", line 111, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\app.py", line 16, in <module>
    from argilla.server.server import app
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\server.py", line 42, in <module>
    from argilla.server.routes import api_router
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\routes.py", line 23, in <module>
    from argilla.server.apis.v0.handlers import (
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\apis\v0\handlers\datasets.py", line 20, in <module>
    from argilla.server.apis.v0.models.commons.params import CommonTaskHandlerDependencies
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\apis\v0\models\commons\params.py", line 24, in <module>
    from argilla.server.security.model import WORKSPACE_NAME_PATTERN
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\security\__init__.py", line 16, in <module>
    from .factory import auth
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\security\factory.py", line 16, in <module>
    from argilla.server.security.auth_provider import create_local_auth_provider
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\security\auth_provider\__init__.py", line 16, in <module>
    from .local import LocalAuthProvider, create_local_auth_provider
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\security\auth_provider\local\__init__.py", line 16, in <module>
    from .provider import LocalAuthProvider, create_local_auth_provider
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\security\auth_provider\local\provider.py", line 40, in <module>
    tokenUrl=local_security.public_oauth_token_url,
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\server\security\auth_provider\local\settings.py", line 53, in public_oauth_token_url
    return f"{server_settings.base_url}{self.token_api_url.removeprefix('/')}"
AttributeError: 'str' object has no attribute 'removeprefix'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\__main__.py", line 19, in <module>
    uvicorn.run(
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\uvicorn\importer.py", line 31, in import_from_string
    instance = getattr(instance, attr_str)
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\utils\utils.py", line 81, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\jedrz\anaconda3\envs\al38\lib\site-packages\argilla\utils\utils.py", line 113, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import argilla.server.app because of the following error (look up to see its traceback):
'str' object has no attribute 'removeprefix'
```

---

Python v3.9.0

After `pip install "argilla[server]==1.2.0"`:

```powershell
>> python -m argilla
Traceback (most recent call last):
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\argilla\utils\utils.py", line 111, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\argilla\server\app.py", line 16, in <module>
    from argilla.server.server import app
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\argilla\server\server.py", line 225, in <module>
    app_configure(argilla_app)
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\argilla\server\server.py", line 111, in configure_app_statics
    temp_statics = _create_statics_folder(statics_folder)
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\argilla\server\server.py", line 105, in _create_statics_folder
    for line in file:
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\fileinput.py", line 249, in __next__
    line = self._readline()
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6985: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\argilla\__main__.py", line 19, in <module>
    uvicorn.run(
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\uvicorn\importer.py", line 31, in import_from_string
    instance = getattr(instance, attr_str)
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\argilla\utils\utils.py", line 81, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\jedrz\anaconda3\envs\al39\lib\site-packages\argilla\utils\utils.py", line 113, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import argilla.server.app because of the following error (look up to see its traceback):
'charmap' codec can't decode byte 0x81 in position 6985: character maps to <undefined>
```

**Comment by dvsrepo** [comment]
Thanks @jamnicki both issues will be fixed in a patch to be released early this week.

In the meantime, with py3.9 you can launch the server with this workaround:

`python -Xutf8 -m argilla`

@frascuchon

**Comment by frascuchon** [comment]
Hi, @jamnicki This problem should be fixed in 1.2.1.

**Comment by frascuchon** [comment]
See #2192 and #2219

**Comment by frascuchon** [comment]
Fixed by #2234  and #2230

**Comment by mancunian1792** [comment]
@frascuchon I have installed 1.6.0 version of argilla and i get this error.

![image](https://user-images.githubusercontent.com/9761766/232852734-a6e963ee-28c8-4ebc-a28e-71401d6fddea.png)
![image](https://user-images.githubusercontent.com/9761766/232852847-aeea7abc-f60b-43d2-8029-be96573b749a.png)
![image](https://user-images.githubusercontent.com/9761766/232853011-f5f1afd9-e8e2-456f-997a-6606a067c4e5.png)

![image](https://user-images.githubusercontent.com/9761766/232853631-a6deef6c-5f1d-4869-a8ca-091f785ec947.png)

Happy to create a separate issue if needed.

**Comment by tomaarsen** [comment]
Please create a new issue for this! Then we can discuss some options there, and others with the same problem may be able to benefit from the issue. In the meantime, you can try to experiment with different versions of `fastapi`, as long as they fall within `>= 0.75,< 0.89`.
