### ISSUE TITLE
`Docker` images are not working and ES versions are mis-aligned in docs

### ISSUE THREAD

**Issue by davidberenstein1957** [recognai/rubrix#2315]
**Describe the bug**
Deploying via individual images show some issues across different OSs (Linux vs MacOS vs Windows). 
Also, ES versions are out-dated in the docs and docker-compose. 
Could you update the docs and add some context as to why certain configs might work and why not.

**To Reproduce**
within MacOS:
works for server
`docker run -p 6900:6900 --name argilla --net=host argilla/argilla-server:latest`
`docker run -p 6900:6900 --name argilla -e "ARGILLA_ELASTICSEARCH=http://local_ip:9200/"  argilla/argilla-server:latest`
these do not work for server
`docker run -p 6900:6900 --name argilla argilla/argilla-server:latest`
`docker run -p 6900:6900 --name argilla -e "ARGILLA_ELASTICSEARCH=http://localhost:9200/"  argilla/argilla-server:latest`
these do not work for quickstart
`docker run -d --name quickstart -p 6900:6900 argilla/argilla-quickstart:latest`
`docker run -d --name quickstart --net=host -p 6900:6900 argilla/argilla-quickstart:latest`

**Expected behavior**

**Screenshots**
N.A.

**Environment (please complete the following information):**
 - OS [e.g. iOS]: MacOS

**Additional context**
N.A.

**Comment by jerpint** [comment]
I'm also unable to run the quickstart docker container succesfully on macOS.

After running:

`docker run -d --name quickstart -p 6900:6900 argilla/argilla-quickstart:latest`

I get the following log:

```
elasticsearch
Creating users schema
Starting Elasticsearch
Waiting for elasticsearch to start
Starting Argilla
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
INFO:     Started server process [180]
INFO:     Waiting for application startup.
Connection to http://localhost:9200 is not ready. Tried 1 times. Retrying...
Connection to http://localhost:9200 is not ready. Tried 2 times. Retrying...
Connection to http://localhost:9200 is not ready. Tried 3 times. Retrying...
Connection to http://localhost:9200 is not ready. Tried 4 times. Retrying...
Connection to http://localhost:9200 is not ready. Tried 5 times. Retrying...
Connection to http://localhost:9200 is not ready. Tried 6 times. Retrying...
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/argilla/server/daos/backend/client_adapters/factory.py", line 90, in _fetch_cluster_version_info
    response = httpx.get(hosts)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_api.py", line 189, in get
    return request(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/argilla/server/server.py", line 142, in _setup_elasticsearch
    backend = GenericElasticEngineBackend.get_instance()
  File "/usr/local/lib/python3.9/dist-packages/argilla/server/daos/backend/generic_elastic.py", line 84, in get_instance
    client=ClientAdapterFactory.get(
  File "/usr/local/lib/python3.9/dist-packages/argilla/server/daos/backend/client_adapters/factory.py", line 45, in get
    ) = cls._resolve_client_class_with_vector_support(hosts)
  File "/usr/local/lib/python3.9/dist-packages/argilla/server/daos/backend/client_adapters/factory.py", line 64, in _resolve_client_class_with_vector_support
    version, distribution = cls._fetch_cluster_version_info(hosts)
elasticsearch
Creating users schema
Starting Elasticsearch
Waiting for elasticsearch to start
  File "/usr/local/lib/python3.9/dist-packages/argilla/server/daos/backend/client_adapters/factory.py", line 99, in _fetch_cluster_version_info
    raise GenericSearchError(error)
argilla.server.daos.backend.base.GenericSearchError: [Errno 99] Cannot assign requested address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/usr/local/lib/python3.9/dist-packages/argilla/server/server.py", line 161, in setup_elasticsearch
    _setup_elasticsearch()
  File "/usr/local/lib/python3.9/dist-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/argilla/server/server.py", line 151, in _setup_elasticsearch
    raise ConfigError(
pydantic.errors.ConfigError: Your Elasticsearch endpoint at http://localhost:9200 is not available or not responding.
Please make sure your Elasticsearch instance is launched and correctly running and
you have the necessary access permissions. Once you have verified this, restart the argilla server.


ERROR:    Application startup failed. Exiting.
```

**Comment by jerpint** [comment]
I also tried `docker run -d --name quickstart --net=host -p 6900:6900 argilla/argilla-quickstart:latest`, same error happens

**Comment by davidberenstein1957** [comment]
Thanks for notifying us. @jerpint I would help to deploy via [docker-compose](https://docs.argilla.io/en/latest/getting_started/installation/deployments/docker_compose.html).

**Comment by davidberenstein1957** [comment]
Hi @jerpint , this might be an Apple silicon issue. There is a `--platform arm64` parameter to overcome this, but this requires a custom built arm64 image, which is not there yet.

@frascuchon will pick this up.

**Comment by davidberenstein1957** [comment]
@jerpint 
this can be resolved, by:

`docker run -d --platform=linux/arm64 --name quickstart -p 6900:6900 argilla/argilla-quickstart:pr-2323`

This will be included in latest during the release 10/02/2023.

**Comment by jerpint** [comment]
Awesome, it works!
