### ISSUE TITLE
node-gyp related error during frontend build

### ISSUE THREAD

**Issue by Ankush-Chander** [recognai/rubrix#2633]
**Describe the bug**

While following [developer documentation](https://docs.argilla.io/en/latest/community/developer_docs.html) 
Following step is giving error:
```
bash scripts/build_frontend.sh
``` 
Error log:

```
npm WARN deprecated nuxt-mq@2.0.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated node-pre-gyp@0.10.3: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> canvas@1.6.13 install /media/workplace/nlp_repos/argilla/frontend/node_modules/canvas
> node-gyp rebuild

/bin/sh: 1: ./util/has_lib.sh: Permission denied
gyp: Call to './util/has_lib.sh jpeg' returned exit status 126 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/hedgeknight/anaconda3/envs/argilla/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.15.0-69-generic
gyp ERR! command "/home/hedgeknight/anaconda3/envs/argilla/bin/node" "/home/hedgeknight/anaconda3/envs/argilla/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/workplace/nlp_repos/argilla/frontend/node_modules/canvas
gyp ERR! node -v v14.17.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> deasync@0.1.28 install /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync
> node ./build.js

`linux-x64-node-14` exists; testing
Problem with the binary; manual build incoming
stdout=
err=Error: Command failed: /home/hedgeknight/anaconda3/envs/argilla/bin/node quick-test.js
/media/workplace/nlp_repos/argilla/frontend/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/build/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/build/Debug/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/build/Release/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/out/Debug/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/Debug/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/out/Release/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/Release/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/build/default/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/compiled/14.17.4/linux/x64/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/lib/binding/node-v83-linux-x64/deasync.node
    at bindings (/media/workplace/nlp_repos/argilla/frontend/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/index.js:30:31)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/quick-test.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14) {
  tries: [
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/build/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/build/Debug/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/build/Release/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/out/Debug/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/Debug/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/out/Release/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/Release/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/build/default/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/compiled/14.17.4/linux/x64/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/addon-build/release/install-root/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/addon-build/debug/install-root/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/addon-build/default/install-root/deasync.node',
    '/media/workplace/nlp_repos/argilla/frontend/node_modules/deasync/lib/binding/node-v83-linux-x64/deasync.node'
  ]
}

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/hedgeknight/anaconda3/envs/argilla/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/hedgeknight/anaconda3/envs/argilla/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/hedgeknight/anaconda3/envs/argilla/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/hedgeknight/anaconda3/envs/argilla/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/hedgeknight/anaconda3/envs/argilla/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/hedgeknight/anaconda3/envs/argilla/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Linux 5.15.0-69-generic
gyp ERR! command "/home/hedgeknight/anaconda3/envs/argilla/bin/node" "/home/hedgeknight/anaconda3/envs/argilla/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/workplace/nlp_repos/argilla/frontend/node_modules/deasync
gyp ERR! node -v v14.17.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
Build failed
npm WARN notsup Unsupported engine for @nuxt/builder@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/builder@2.16.3
npm WARN notsup Unsupported engine for @nuxt/babel-preset-app@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/babel-preset-app@2.16.3
npm WARN notsup Unsupported engine for @nuxt/cli@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/cli@2.16.3
npm WARN notsup Unsupported engine for @nuxt/config@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/config@2.16.3
npm WARN notsup Unsupported engine for @nuxt/core@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/core@2.16.3
npm WARN notsup Unsupported engine for @nuxt/generator@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/generator@2.16.3
npm WARN notsup Unsupported engine for @nuxt/server@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/server@2.16.3
npm WARN notsup Unsupported engine for @nuxt/utils@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/utils@2.16.3
npm WARN notsup Unsupported engine for @nuxt/vue-app@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/vue-app@2.16.3
npm WARN notsup Unsupported engine for @nuxt/vue-renderer@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/vue-renderer@2.16.3
npm WARN notsup Unsupported engine for @nuxt/webpack@2.16.3: wanted: {"node":"^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0"} (current: {"node":"14.17.4","npm":"6.14.14"})
npm WARN notsup Not compatible with your version of node/npm: @nuxt/webpack@2.16.3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.13 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.13 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.28 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deasync@0.1.28 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hedgeknight/.npm/_logs/2023-04-01T07_26_01_863Z-debug.log

```

**Expected behavior**
Should build the frontend without any implicit system requirement or undocumented prerequisites. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser [e.g. chrome, safari]:
 - Argilla Version [e.g. 1.0.0]: 
 - ElasticSearch Version [e.g. 7.10.2]:
 - Docker Image (optional) [e.g. argilla:v1.0.0]:

**Additional context**

**Comment by frascuchon** [comment]
Hi @Ankush-Chander , 

I've seen this error before and it's related to the nodejs version, did you try a version upgrade?
