### ISSUE TITLE
Error when running snorkel_model.fit

### ISSUE THREAD

**Issue by leachader** [recognai/rubrix#2959]
Hi Team,
Hope you are doing well.
I have a dataset which I split in "metadata.split:test" and "metadata.split:unlabelled" to do weaklearning and run a snorkel model. I had made a first run where I added the snorkel predictions in the dataset. When running snorkel_model.fit again though, I am getting the following error: ValueError: zero-size array to reduction operation maximum which has no identity. Is this expected behavior?
Thank you,
Lea

Environment Info:
 - OS: 64-bit windows
 - Browser: chrome
 - Argilla Version: 1.7.0

**Comment by leachader** [comment]
Hi Team,
I've made some tests and it seems that the error occurs only when the dataset already has predictions that were added to it.
Also, please find below the stacktrace:

**Comment by leachader** [comment]
Hi Team,
I've made some tests and it seems that the error occurs only when the dataset already has predictions that were added to it.
Also, please find below the stacktrace. Let me know if anything else is needed :) 

Traceback (most recent call last):                                                                          
File "main.py", line 146, in <module>                                                                     
 main(logger=logger, conf=conf)                                                                          
File "main.py", line 71, in main                                                                          
 label_class.train_predict_snorkel(weak_labels)                                                          
File "/home/jovyan/thesis_510/src/labeling/labeling.py", line 127, in train_predict_snorkel               
 snorkel_model.fit(lr=0.001, n_epochs=50)                                                                
File                                                                                                      
"/opt/conda/lib/python3.8/site-packages/argilla/labeling/text_classification/label_models.py",              
line 504, in fit                                                                                            
 self._model.fit(L_train=l_train, **kwargs)                                                              
File "/opt/conda/lib/python3.8/site-packages/snorkel/labeling/model/label_model.py", line 892,            
in fit                                                                                                      
 if L_shift.max() > self.cardinality:                                                                    
File "/opt/conda/lib/python3.8/site-packages/numpy/core/_methods.py", line 40, in _amax                   
 return umr_maximum(a, axis, None, out, keepdims, initial, where)                                        
ValueError: zero-size array to reduction operation maximum which has no identity
