### ISSUE TITLE
[BUG-python/deployment] ValueError: Unable to create tensor

### ISSUE THREAD

**Issue by 7flash** [recognai/rubrix#4513]
Following this tutorial:

https://docs.argilla.io/en/latest/tutorials_and_integrations/tutorials/feedback/training-llm-mistral-sft.html#ArgillaTrainer-&-hyperparameters

```
data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)
trainer.update_config(
    data_collator=data_collator
)
trainer.train("Mistral-7B-v0.1-chat-OIG-3k")
```

It gives me an error:

```
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with
'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features
(`text` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```

**Comment by 7flash** [comment]
The actual error:

```
  0%|                                                                         | 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 748, in convert_to_tensors
    tensor = as_tensor(value)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 720, in as_tensor
    return torch.tensor(value)
ValueError: too many dimensions 'str'
```

**Comment by 7flash** [comment]
It happens after warning:

```
/usr/local/lib/python3.10/dist-packages/trl/trainer/sft_trainer.py:284: UserWarning: You passed a tokenizer with `padding_side` not equal to `right` to the SFTTrainer. This might lead to some unexpected behaviour due to overflow issues when training a model in half-precision. You might consider adding `tokenizer.padding_side = 'right'` to your code.
```

**Comment by davidberenstein1957** [comment]
@7flash did you follow the tutorial step by step or change something small?

**Comment by 7flash** [comment]
This is full script I am running, following tutorial step by step:

```
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

from typing import Dict, Iterator, Any
from argilla.feedback import TrainingTask
from transformers import DataCollatorForLanguageModeling
from transformers import DataCollatorForSeq2Seq, BatchEncoding
from typing import Optional
import torch
from transformers import TrainerCallback, TrainerControl, TrainerState, GenerationConfig, TrainingArguments, PreTrainedModel, PreTrainedTokenizer
from argilla.feedback import ArgillaTrainer
from peft import LoraConfig, TaskType
import argilla as rg

model_id = "mistralai/Mistral-7B-v0.1"
model = AutoModelForCausalLM.from_pretrained(model_id, torch_dtype=torch.float16, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token_id = tokenizer.eos_token_id

ANNOTATED_ONLY = False

def formatting_func(sample: Dict[str, Any]) -> Iterator[str]:
    if ANNOTATED_ONLY:
        # Discard if there are no annotations...
        if not sample["quality"]:
            return

        # or if it is annotated as "Bad" or discarded.
        first_annotation = sample["quality"][0]
        if first_annotation["value"] == "Bad" or first_annotation["status"] == "discarded":
            return

    # Filter out responses that are likely low quality
    if len(sample["response"]) <= 2:
        return

    # Add </s><s> between all prompt-response pairs
    prompt = sample["prompt"]
    prompt = prompt.replace("<human>:", f"{tokenizer.eos_token}{tokenizer.bos_token}<human>:")
    prompt = prompt[prompt.find("<human>:"):]
    # Add response and optionally the background to the full text.
    output = prompt + " " + sample["response"]
    if sample["background"]:
        output = sample["background"] + " " + output
    output = output + tokenizer.eos_token
    # We expect one less <s> than </s>, because the Mistral tokenizer will automatically add the BOS
    # at the start of the text when this text is tokenized. When that's done, the format will be exactly
    # what we want
    assert output.count("<s>") + 1 == output.count("</s>")
    return output

task = TrainingTask.for_supervised_fine_tuning(formatting_func)

dataset = rg.FeedbackDataset.from_argilla("oig-30k")

formatted_dataset = dataset.prepare_for_training(framework="trl", task=task)

print(formatted_dataset[80]["text"])

data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False)
data_collator([tokenizer(formatted_dataset[0]["text"])])

class GenerationCallback(TrainerCallback):
    def __init__(self, prompt: str) -> None:
        super().__init__()
        self.prompt = prompt

    def on_evaluate(self, args: TrainingArguments, state: TrainerState, control: TrainerControl, model: Optional[PreTrainedModel] = None, tokenizer: Optional[PreTrainedTokenizer] = None, **kwargs):
        # Tokenize the prompt and send it to the right device
        inputs = tokenizer(self.prompt, return_tensors="pt").to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                generation_config=GenerationConfig(
                    max_new_tokens=50,
                    pad_token_id=tokenizer.pad_token_id,
                    eos_token_id=tokenizer.eos_token_id,
                ),
            )
            print(tokenizer.batch_decode(outputs, skip_special_tokens=False)[0])


generation_callback = GenerationCallback("<human>: What were Nelson Mandela's relations with the ANC? <bot>:")

trainer = ArgillaTrainer(
    dataset=dataset,
    model=model,
    tokenizer=tokenizer,
    task=task,
    framework="trl",
    train_size=0.9,
)



peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
)
trainer.update_config(
    data_collator=data_collator,
    callbacks=[generation_callback],
    peft_config=peft_config,
    max_seq_length=1024,
)

trainer.update_config(
    per_device_train_batch_size=3,
    per_device_eval_batch_size=3,
    eval_accumulation_steps=16,
    max_steps=3000,
    logging_steps=50,
    learning_rate=5e-5,
    save_strategy="no",
    evaluation_strategy="steps",
    eval_steps=500,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    remove_unused_columns=False,
    fp16=True,
    num_train_epochs=1,
)

trainer.train("Mistral-7B-v0.1-chat-OIG-3k")

```

**Comment by 7flash** [comment]
Okay so how do I change data_collator when passing it to config?

**Comment by nataliaElv** [comment]
Hi @7flash ! Did you manage to solve this issue or do you still need help with it?
